name: Prevent Push to Restricted Branch

on:
  push:
    branches: [ main ] # Replace with the name of your restricted branch

jobs:
  prevent-push:
    runs-on: ubuntu-latest

    steps:
      - name: Block Push to main
        run: |
          if [ "${{ github.event.pull_request.head.ref }}" == "main" ]; then
           echo "Merges to main are only allowed from the PR."
           exit 1
          fi 
