name: Prevent Push to Restricted Branch

on:
  push:
    branches: [ main ] # Replace with the name of your restricted branch

jobs:
  prevent-push:
    runs-on: ubuntu-latest

    steps:
      - name: Block Push to main
        run: |
          echo "Pushes to the main are not allowed."
          exit 1
