name: Prevent Push to Restricted Branch

on:
  push:
    branches: [ main ] # Replace with the name of your restricted branch

jobs:
  prevent-push:
    runs-on: ubuntu-latest

    steps:
     - name: Check merge branch
       if: github.event.pull_request.base.ref == 'main'
       run: |
         if [ "${{ github.event.pull_request.head.ref }}" != "release/QA" ]; then
           echo "Merges to main are only allowed from the release/QA branch."
           exit 1
         fi 
